#!/usr/bin/env bash

# based on the original github command

set -eo pipefail

COMMAND=$(echo "$1" | jq -r '.command')

set -e
alias sunbeam='/Users/bper/dev/sunbeam-main/sunbeam'

# if no arguments are passed, return the extension's manifest
if [ $# -eq 0 ]; then
    sunbeam query -n '
{
    title: "GitHub",
    commands: [
        { name: "list-repos", mode: "list", title: "List Repos" },
        { name: "list-issues", mode: "list", title: "List Issue", params: [{ name: "repo", type: "string", required: true, description: "the repository to search for" }] },
        { name: "list-prs", mode: "list", title: "List PRs", params: [{ name: "repo", type: "string", required: true, description: "the repository to search for" }] }
    ]
}'
exit 0
fi

if [[ $COMMAND == "list-repos" ]]; then
    # shellcheck disable=SC2016
    gh api "/user/repos?sort=updated&per_page=100" | sunbeam query --arg "command=$0" '[ .[] |
        {
            title: .name,
            subtitle: (.description // ""),
            accessories: [
                "\(.stargazers_count) *"
            ],
            actions: [
                {
                    title: "Open",
                    type: "open",
                    target: .html_url
                },
                {
                    title: "List Pull Requests",
                    type: "run",
                    command: "list-prs",
                    params: {repo: .full_name},
                    key: "p"
                },
                {
                    title: "List Issues",
                    key: "i",
                    type: "run",
                    command: "list-issues",
                    params: {repo: .full_name}
                }
            ]
        }
    ] | { "items" : .}'
    exit 0
elif [[ $COMMAND == "list-prs" ]]; then
    REPO=$(echo "$1" | sunbeam query -r '.params.repo')

    gh pr list --repo "$REPO" --json author,title,url,number | sunbeam query '[ .[] |
    {
        title: .title,
        subtitle: .author.login,
        accessories: [
            "#\(.number)"
        ],
        actions: [
            {
                title: "Open in Browser",
                type: "open",
                target: .url
            },
            {
                title: "Copy URL",
                type: "copy",
                text: .url
            }
        ]
    }
    ] | { "items" : .}'
    exit 0
elif [[ $COMMAND == "list-issues" ]]; then
    REPO=$(echo "$1" | sunbeam query -r '.params.repo')

    gh issue list --repo "$REPO" --json author,title,url,number | sunbeam query '[ .[] |
    {
        title: .title,
        subtitle: .author.login,
        accessories: [
            "#\(.number)"
        ],
        actions: [
            {
                title: "Open in Browser",
                type: "open",
                target: .url
            },
            {
                title: "Copy URL",
                type: "copy",
                text: .url
            }
        ]
    }
    ] | { "items" : . }'
    exit 0
fi
