#!/usr/bin/env bash

# based on the original github command

set -eo pipefail

COMMAND="${1:-list-repos}"

if [[ $COMMAND == "list-repos" ]]; then
    # shellcheck disable=SC2016
    gh api "/user/repos?sort=updated&per_page=100" | sunbeam query --arg "command=$0" '.[] |
        {
            title: .name,
            subtitle: (.description // ""),
            accessories: [
                "\(.stargazers_count) *"
            ],
            actions: [
                {type: "open", target: .html_url},
                {
                    type: "push",
                    title: "List Pull Requests",
                    key: "p",
                    command: [$command, "list-prs", .full_name],
                },
                {
                    type: "push",
                    title: "List Issues",
                    key: "i",
                    command: [$command, "list-issues", .full_name],
                }
            ]
        }
    ' | sunbeam list --json --title "List Repositories"
elif [[ $COMMAND == "list-prs" ]]; then
    REPO=$2
    if [[ -z "$REPO" ]]; then
        echo "Usage: $0 list-prs <repo>"
        exit 1
    fi

    gh pr list --repo "$REPO" --json author,title,url,number | sunbeam query '.[] |
    {
        title: .title,
        subtitle: .author.login,
        accessories: [
            "#\(.number)"
        ],
        actions: [
            {type: "open", title: "Open in Browser", target: .url},
            {type: "copy", title: "Copy URL", text: .url}
        ]
    }
    ' | sunbeam list --json --title "List Pull Requests"
elif [[ $COMMAND == "list-issues" ]]; then
    REPO=$2
    if [[ -z "$REPO" ]]; then
        echo "Usage: $0 list-prs <repo>"
        exit 1
    fi

    gh issue list --repo "$REPO" --json author,title,url,number | sunbeam query '.[] |
    {
        title: .title,
        subtitle: .author.login,
        accessories: [
            "#\(.number)"
        ],
        actions: [
            {type: "open", title: "Open in Browser", target: .url},
            {type: "copy", title: "Copy URL", text: .url}
        ]
    }
    ' | sunbeam list --json --title "List Issues"
fi