#!/usr/bin/env bash

set -eo pipefail

COMMAND=$(echo "$1" | jq -r '.command')
PROVIDERS='["dbt-labs/dbtcloud", "GtheSheep/dbt-cloud", "fivetran/fivetran", "Snowflake-Labs/snowflake", "databricks/databricks", "integrations/github"]'

if [ $# -eq 0 ]; then
/Users/bper/dev/sunbeam-main/sunbeam query -n '{
    title: "TF",
    commands: [
        {name: "list-providers", mode: "page", title: "List Providers"},
        {name: "list-releases", mode: "page", title: "List Releases", params: [{name: "provider", type: "string", required: true}]},
        {name: "show-details", mode: "page", title: "Show Details", params: [{name: "id", type: "string", required: true}, {name: "version", type: "string", required: true}]}
    ]
}'
exit 0
fi


if [[ $COMMAND == "list-providers" ]]; then

    echo $PROVIDERS |  /Users/bper/dev/sunbeam-main/sunbeam query --arg "command=$0" '
        {
        type: "list",
        items: map({
            title: .,
            actions: [{
            title: "List releases",
            type: "run",
            command: "list-releases",
            params: { provider: . }
            }]
        })
        }'
     exit 0

elif [[ $COMMAND == "list-releases" ]]; then

    PROVIDER=$(echo "$1" | sunbeam query -r '.params.provider')
    versions=$(curl "https://registry.terraform.io/v2/providers/${PROVIDER}?include=categories,moved-to,potential-fork-of,provider-versions,top-modules&include=categories%2Cmoved-to%2Cpotential-fork-of%2Cprovider-versions%2Ctop-modules")

    ID=$(echo $versions | jq -r '.data.id')

    echo $versions |  /Users/bper/dev/sunbeam-main/sunbeam query --arg "command=$0" --arg "provider=${PROVIDER}"  --arg "id=${ID}" '
        {
        type: "list",
        title: "List of releases",
        items:
            (.included | sort_by(.attributes["published-at"]) | reverse | map({
            title: (.attributes.version // "ALL"),
            subtitle: (.attributes["published-at"][:10] // "N/A"),
            accessories: [(.attributes.downloads | tostring)],
            actions: [
                {
                    title: "Download details",
                    type: "run",
                    command: "show-details",
                    params: { id: $id, version: (.attributes.version // "") }
                },
                {
                    title: "Open in Browser",
                    key: "o",
                    type: "open",
                    target: ("https://registry.terraform.io/providers/" + $provider + "/" + (.attributes.version // ""))
                }
            ]
            }))
        }'
     exit 0


elif [[ $COMMAND == "show-details" ]]; then

    PARAMS=$(echo "$1" | sunbeam query '.params')
    ID=$(echo $PARAMS | sunbeam query -r '.id')
    VERSION=$(echo $PARAMS | sunbeam query -r '.version')

    details=$(curl "https://registry.terraform.io/v2/providers/${ID}/downloads/summary?filter%5Bversion%5D=${VERSION}")

    echo $details | /Users/bper/dev/sunbeam-main/sunbeam query '
        {
            type: "list",
            items: [
                {
                    title: "This week",
                    subtitle: (.data.attributes.week | tostring)
                },
                {
                    title: "This month",
                    subtitle: (.data.attributes.month | tostring)
                },
                {
                    title: "This year",
                    subtitle: (.data.attributes.year | tostring)
                },
                {
                    title: "Total",
                    subtitle: (.data.attributes.total | tostring)
                }
            ]
        }'

fi
