#! /bin/bash

source ~/.sunbeamrc

if [ $# -eq 0 ]; then
    sunbeam query -n '
{
    title: "Harvest",
    commands: [
        { name: "list-projects", mode: "list", title: "List Projects" },
        { name: "detail-project", mode: "list", title: "Detail Project", params: [{ name: "project_id", type: "string", required: true }]}
    ]
}'
exit 0
fi

COMMAND=$(echo "$1" | jq -r '.command')
if [[ $COMMAND == "list-projects" ]]; then
    timesheets=$(curl -s --request GET \
    --url "https://api.harvestapp.com/api/v2/time_entries?user_id=${SB_HARVEST_USERID}&from=2022-01-01" \
    --header "authorization: Bearer ${SB_HARVEST_TOKEN}" \
    --header "harvest-account-id: ${SB_HARVEST_ACCOUNT}" | jq '[.time_entries[] | select(.billable == true)] | group_by(.project.id)  | map({project_id: first.project.id | tostring, hours: (map(.hours) | add)})')

    projects=$(curl -s --request GET \
    --url https://api.harvestapp.com/api/v2/projects \
    --header "authorization: Bearer ${SB_HARVEST_TOKEN}" \
    --header "harvest-account-id: ${SB_HARVEST_ACCOUNT}" | jq '[.projects[] | select(.is_active == true) | {project_id: .id | tostring, name: .name, budget: .budget, client: .client.name}]')

    results=$(jq -n --argjson projects "$projects" --argjson timesheets "$timesheets" '[JOIN(INDEX($projects[]; .project_id); $timesheets[]; .project_id; add) | select(.client) | . += {url: ("'$SB_HARVEST_URL'/projects/" + .project_id)}]')

    echo $results | sunbeam query '[ .[] |
    {
        title: (.client + " - " + .name),
        subtitle: ((.hours | tostring) + " / " + (.budget | tostring)),
        actions: [
            {
                title: "Open Harvest",
                type: "open",
                target: .url
            },
            {
                title: "Add Time",
                key: "a",
                type: "open",
                target: "'$SB_HARVEST_URL'/time/week"
            },
            {
                title: "Copy Hours",
                key: "l",
                type: "copy",
                text: .hours | tostring
            },
            {
                title: "Details",
                key: "d",
                type: "run",
                command: "detail-project",
                params: {project_id: .project_id}
            }
        ]
    }
    ] | { "title" : "Harvest", "items" : . }'
    exit 0
fi


if [[ $COMMAND == "detail-project" ]]; then

    PROJECT_ID=$(echo "$1" | sunbeam query -r '.params.project_id')

    details=$(curl -s --request GET \
    --url "https://api.harvestapp.com/api/v2/time_entries?project_id=${PROJECT_ID}" \
    --header "authorization: Bearer ${SB_HARVEST_TOKEN}" \
    --header "harvest-account-id: ${SB_HARVEST_ACCOUNT}")

    parsed_details=$(echo $details | sunbeam query '[
        .time_entries[]
        | {task_name: .task.name, user_name: .user.name, billable: .billable, hours: .hours}
    ] | group_by(.task_name, .user_name, .billable)
    | map({
        task: [.[0].task_name, .[0].user_name , if .[0].billable then "Billable" else "Non Billable" end] | join(" - "),
        total_hours: map(.hours) | add
    })')

    echo $parsed_details | sunbeam query '[ .[] |
    {
        title: .task,
        subtitle: .total_hours | tostring,
    }
    ] | { "title" : "Harvest", "items" : . }'
    exit 0
fi
