#!/bin/sh

# check if python3 is installed
if ! command -v python3 >/dev/null 2>&1; then
    echo "python3 is not installed"
    exit 1
fi

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
exec python3 "$DIR/extension.py" "$@"
